index:
    path: /
    controller: App\Controller\IndexController::index
api_login_check:
    path: /api/login_check
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
_swagger-ui:
    resource: '@HBSwaggerUiBundle/Resources/config/routing.yml'
    prefix: /api/docs